spring:
  application:
    name: application-front
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    throw-exception-if-no-handler-found: false

server:
  port: 80
  error:
    whitelabel:
      enabled: false